### ISSUE TITLE
travis ci no longer configured

### ISSUE THREAD

**Issue by tjbaker** [ThoughtWorksInc/aws_role_credentials#3]
CONTRIBUTING.rst mentions Travis builds at an inactive location.  The repo has moved and builds don't appear to be configured.

https://github.com/ThoughtWorksInc/aws_role_credentials/blame/master/CONTRIBUTING.rst#L103

**Comment by petergillardmoss** [comment]
The Travis CI was generated from a template.

I've added a Snap CI build along with links and badges.

Thanks
Peter
